name: Run Scraper

on:
  push:
    branches:
      - main  # Runs the scraper when code is pushed to the main branch
  workflow_dispatch: # Allows manual triggering of the scraper through the GitHub UI

jobs:
  run_scraper:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12  # Make sure to use the version of Python you're working with

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure that you have a requirements.txt file

      # Step 4: Run the crawler script
      - name: Run Crawler
        run: |
          python dashboard.py  # Change this to your actual script name if it's different
